title: Orchid Wiki
description: Orchid Wiki
remote_theme: just-the-docs/just-the-docs

favicon_ico: "/favicon.ico"

url: https://wiki.orchidmc.me

aux_links:
  Contribute: https://github.com/orchidtowny/wiki

footer_content: "Written with care by the Orchid Community"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
