title: Orchid Wiki
description: Orchid Wiki
remote_theme: just-the-docs/just-the-docs

favicon_ico: "/favicon.ico"

url: https://wiki.orchidmc.me

aux_links:
  Contribute: https://github.com/orchidtowny/wiki
